# scripts/run-sllidar-template.sh
#!/bin/sh
#
# This script is generated by the Nix flake.
#

# Source the necessary ROS setup
source @ROS_CORE_SETUP@

# Source the workspace setup to find the launch file
source @WORKSPACE_SETUP@

# Run the launch file
exec ros2 launch sllidar_ros2 view_sllidar_a2m12_launch.py "$@"